[tool.poetry]
name = "naiive-bayes"
version = "0.1.0"
description = "Hy implementation of Naiive Bayes"
authors = ["Josiah Berkebile <praenato14@gmail.com>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "3.7.9"
appdirs = "1.4.3"
astor = "0.8.1"
calysto-hy = "0.1.1"
funcparserlib = "0.3.6"
metakernel = "0.24.4"
rply = "0.7.7"
toolz = "0.10.0"
matplotlib = "3.3.0"
seaborn = "0.10.1"
hy = "0.19.0"
jedhy = "1"
black = "^20.8b1"
pysqlite3 = "^0.4.3"
pandas = "1.1.3"
numpy = "1.19.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
